image: gitpod/workspace-full

tasks:
  - init: mvn install
    command: |
      docker-compose up -d
      ./mvnw spring-boot:run

ports:
  - port: 8080
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
